fix http bytes-object required error in python 3
This fixes the following error
```
    An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/states/http.py", line 95, in query
                  if match in data.get('text', ''):
              TypeError: a bytes-like object is required, not 'str'
```